[settings]
idiomatic_version_file_enable_tools = ["ruby", "terraform"]

[settings.ruby]
compile = false

[tools]
go = "latest"
node = "latest"
ruby = "latest"

# CLI tools
starship = "latest"
github-cli = "latest"
ripgrep = "latest"
jq = "latest"
shellcheck = "latest"
overmind = "latest"
k9s = "latest"
helm = "latest"
tflint = "latest"
bik = "latest"
"github:buildkite/cli" = "latest"
"github:buildkite/agent" = "latest"

# Ruby gems
"gem:ruby-lsp" = "latest"
